---
deployment:
  tasks:
    - export DEPLOYPATH=/home/babysywr/public_html/wp-content/plugins
    - /bin/cp -r plugins/babyswim-kursoversikt $DEPLOYPATH/babyswim-kursoversikt-2
    - /bin/cp -r plugins/right-now-extra $DEPLOYPATH/right-now-extra-2